webtech-translation/scorecard/urls.py
from django.conf.urls import patterns, url

from scorecard import views

urlpatterns = patterns('',
                       url(r'^$', views.IndexView.as_view(), name='index'),
                       url(r'^vote/(?P<pk>\d+)/(?P<vote>-?\d)/$', views.vote, name='vote'),
                       url(r'^details/(?P<pk>\d+)$', views.details, name='details'),
                       url(r'^vote_again$', views.vote_again, name='vote_again'),
                       url(r'^statistics', views.statistics, name="statistics"),
                       )

webtech-translation/webtech/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'webtech.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),

                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^scorecard/', include('scorecard.urls', namespace="scorecard")),
)

webtech-translation/scorecard/models.py
from django.db import models


class Lecturer(models.Model):
    """
    This class stores the information about one lecturer
    first_name  is the field which stores the first name
    last_name   is the field which stores the last name
    pk          is created automatically as the primary key
    """
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)

    def __str__(self):
        """
        Convert the Lecturer Name to a human readable string
        :return: Returns the full name of the lecturer
        """
        return "{0} {1}".format(self.first_name, self.last_name)


class Course(models.Model):
    """
    This class stores the information about one course
    course_title    is the field which stores the title of a course
    vote            is the number of votes a course got
    lecturer        refers to the Lecturer model and identifies the lecturer responsible for the course
    pk              is created automatically as the primary key
    """
    course_title = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    lecturer = models.ForeignKey(Lecturer)

    def __str__(self):
        """
        Convert a Course Model to a human readable string
        :return: Returns the title of the course
        """
        return self.course_title

    def is_great_course(self):
        """
        Figures out if a course is great or not.
        Great courses have more than 100 positive votes
        :return: True if votes > 100, Fales otherwise
        """
        return self.votes > 100

webtech-translation/scorecard/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.views import generic
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.utils.translation import ugettext as _
from django.db.models import Avg
import sys

from scorecard.models import Course, Lecturer


def redirect_to_index():
    return HttpResponseRedirect(reverse('scorecard:index'))

def update_vote(course, vote):
    vote = int(vote)
    if abs(vote) == 1:
        course.votes += vote
        course.save()
        return True
    return False

def set_voted(request, voted):
    request.session['has_voted'] = voted

def has_already_voted(request):
    return request.session.get('has_voted', False)

def get_best_lecturer_with_mean():
    best_lecturer = None
    best_lecturer_mean = -sys.maxsize
    lecturer_votes = Course.objects.values('lecturer').annotate(avg_votes=Avg('votes'))
    for lecturer_vote in lecturer_votes:
        if lecturer_vote['avg_votes'] > best_lecturer_mean:
            best_lecturer = lecturer_vote['lecturer']
            best_lecturer_mean = lecturer_vote['avg_votes']
    best_lecturer = Lecturer.objects.get(pk=best_lecturer)
    return best_lecturer, best_lecturer_mean

def vote(request, pk, vote):
    """
    You can either up- or down-vote a course
    The vote is saved in the model
    Then the user is redirected to the index page
    :param request: Request to work on
    :param pk:      Primary key of the Course
    :param vote:    1 or -1 depending on up/down-vote
    :return:        Redirect to Index view or 404 error
    """
    # If there is no course with the corresponding pk return an error
    course = get_object_or_404(Course, pk=pk)
    if has_already_voted(request):
        messages.add_message(request, messages.ERROR, _("You have already voted!"))
    elif update_vote(course, vote):
        set_voted(request, True)
        messages.add_message(request, messages.SUCCESS, _("Vote Successful!"))
    else:
        # Vote invalid
        messages.add_message(request, messages.ERROR, _("Vote Not Successful!"))
    return redirect_to_index()


def statistics(request):
    """
    Show statistics page
    :param request:
    :return:
    """
    best_lecturer, best_lecturer_mean = get_best_lecturer_with_mean()
    context = {
        'lecturer_count': Lecturer.objects.count(),
        'courses_count': Course.objects.count(),
        'courses_votes_mean': Course.objects.aggregate(Avg('votes'))['votes__avg'],
        'lecturer_best': best_lecturer,
        'lecturer_best_votes_mean': best_lecturer_mean,
    }
    return render(request, 'scorecard/statistics.html', context)


def vote_again(request):
    """
    Remove vote counter from session
    :param request:
    :return:
    """
    set_voted(request, False)
    return redirect_to_index()


def details(request, pk):
    """
    Show details page for course with primary key pk
    :param request:
    :param pk:
    :return:
    """
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'scorecard/details.html', {'course': course})


class IndexView(generic.ListView):
    """
    The index page is a generic ListView.
    All Courses are shown in a list
    """
    template_name = 'scorecard/index.html'  # Template to use
    model = Course  # Model to use

    def get_queryset(self):
        """
        Order the Courses by their votes begining from the course with most votes.
        """
        return Course.objects.get_queryset().order_by('-votes')

webtech-translation/scorecard/templates/scorecard/base.html
{% load i18n %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>{% block title %}Scorecard{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'scorecard/bootstrap/css/bootstrap.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'scorecard/style.css' %}" />
</head>
<body>
    <div class="container">

    <div class="page-header"><h1><a href="{% url 'scorecard:index' %}">Scorecard</a> <small>{% trans "A" %} <a href="https://wwwmatthes.in.tum.de/pages/g78qcvnwz3u3/Web-Technologies-Frameworks-Libraries-and-Plattforms" target="_blank">webtech</a> {% trans "page by" %} <a href="http://phynformatik.de/" target="_blank">Janosch Maier</a></small> <span id="tumlogo">TUM</span> <span id="inlogo">in.tum</span></h1></div>

        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'scorecard:index' %}">{% trans "Home" %}</a></li>
                        <li><a href="{% url 'scorecard:statistics' %}">{% trans "Statistics" %}</a></li>
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
        </nav>

        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>
        {% endfor %}
    {% endif %}
        {% block content %}{% endblock %}
    </div>
</body>
</html>

webtech-translation/scorecard/templates/scorecard/details.html
{% extends 'scorecard/base.html' %}
{% load i18n %}

{% block content %}
    {% if course %}
        <h2>Course Overview</h2>
        <table class="table">
            <tr>
                <td>{% trans "Title" %}</td>
                <td>{{ course }}</td>
            </tr>
            <tr>
                <td>{% trans "Lecturer" %}</td>
                <td>{{ course.lecturer }}</td>
            </tr>
            <tr>
                <td>{% trans "Votes" %}</td>
                <td>{{ course.votes }}</td>
            </tr>
        </table>
    {% else %}
        <!-- Show an error if no course existing -->
        <div class="alert alert-info" role="alert">{% trans "Course not available." %}</div>
    {% endif %}

{% endblock %}

webtech-translation/scorecard/templates/scorecard/index.html
{% extends 'scorecard/base.html' %}
{% load i18n %}

{% block content %}
    {% if object_list %}
        <ul>
        <!-- Iterate over the courses -->
            {% for course in object_list %}
                <!-- List a course and the voting possibilities -->
                <li><strong><a href="{% url 'scorecard:details' course.pk %}">{{ course }}</a></strong> {% trans "has" %} {% blocktrans count counter=course.votes %}{{ counter }} vote.{% plural %}{{ counter }} votes.{% endblocktrans %}
                    (<a href="{% url 'scorecard:vote' course.pk 1 %}"><span class="glyphicon glyphicon glyphicon-thumbs-up" aria-hidden="true"></span></a>
            <a href="{% url 'scorecard:vote' course.pk -1 %}"><span class="glyphicon glyphicon glyphicon-thumbs-down" aria-hidden="true"></span></a>)
        </li>
    {% endfor %}
    </ul>
    {% if request.session.has_voted %}
        <div class="alert alert-info">
        {% trans "You usually can only vote once. If you want to vote again, I can make an exception for you." %} <a href="{% url 'scorecard:vote_again' %}">{% trans "Vote again?" %}</a>
        </div>
    {% endif %}
    {% else %}
        <!-- Show an error if no course existing -->
        <div class="alert alert-info" role="alert">{% trans "No courses available" %}</div>
    {% endif %}
{% endblock %}

webtech-translation/scorecard/templates/scorecard/statistics.html
{% extends 'scorecard/base.html' %}
{% load i18n %}

{% block content %}
        <h2>{% trans "Statistics" %}</h2>
        <table class="table">
            <tr>
                <td>{% trans "Number of Lecturers" %}</td>
                <td>{{ lecturer_count }}</td>
            </tr>
            <tr>
                <td>{% trans "Number of Courses" %}</td>
                <td>{{ courses_count }}</td>
            </tr>
            <tr>
                <td>{% trans "Votes Mean" %}</td>
                <td>{{ courses_votes_mean }}</td>
            </tr>
            <tr>
                <td>{% trans "Lecturer with Highest Votes" %}</td>
                <td>{{ lecturer_best }}</td>
            </tr>
            <tr>
                <td>{% trans "Votes Mean for" %} {{ lecturer_best }}</td>
                <td>{{ lecturer_best_votes_mean }}</td>
            </tr>
        </table>
{% endblock %}